### ISSUE TITLE
Create uninstall script

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-network#8]
**Description**
Since we do not have a way to change the Gaia directory names without a lot of work, a hack is to create an uninstall script that uninstalls all files that we installed on the user’s machine.

**Tasks**
- [x] Create an uninstall script that uninstalls all files that we installed on the user’s machine.
- [x] Add uninstall instructions to the installer script.

**Comment by faddat** [comment]
1/2 complete

**Comment by faddat** [comment]
2/2 complete @ 643b18ebf0760f45942111d583cb49a2669cfc0f

**Comment by guylepage3** [comment]
Nicely done @faddat
